---
- name: Deploy Ansible and dependencies
  become: true
  gather_facts: true
  hosts: all

  vars:
    packages:
      - gcc
      - libffi-devel
      - openssh-clients
      - git
      - yum-utils
      - python3
      - python3-pip
      - python3-pip-wheel
    pip_packages:
      - ansible
      - pywinrm
      - requests-credssp

  tasks:
    - name: Install system packages
      ansible.builtin.package:
        name: "{{ package }}"
        state: present
      loop: "{{ packages }}"
      loop_control:
        loop_var: package

    - name: Install pip packages
      ansible.builtin.pip:
        name: "{{ pip_package }}"
        state: present
      loop: "{{ pip_packages }}"
      loop_control:
        loop_var: pip_package
